### ISSUE TITLE
Similar repo already exists

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/TheAlgorithms.github.io#2]
A repo made for the same purpose already exists. Can we club them? 
https://github.com/TheAlgorithms/website

**Comment by cclauss** [comment]
@mrmaxguns, @viragumathe5, @shreyasminocha It would be cool if you could attack #1 and build us a web presence that is slicker than the current https://github.com/TheAlgorithms/website and https://TheAlgorithms.github.io.  This is an area where I have no expertise so you folks will need to compare notes and collaborate to build something that will excite visitors.

No matter which language repo that visitors come to, it would be awesome if clicking on the `wiki` tab presented something cooler than https://github.com/TheAlgorithms/Go/wiki

![Wiki Tab](https://user-images.githubusercontent.com/3709715/81261951-43049500-903d-11ea-8b69-d4179572a989.png)


Thanks for your interest and efforts.

**Comment by viragumathe5** [comment]
@cclauss on it, Thank you for tagging

**Comment by viragumathe5** [comment]
@mrmaxguns, @shreyasminocha can we collab???

**Comment by shreyasminocha** [comment]
@viragumathe5 I can't play an active role at this point, but sure! I'll help out with whatever I can.

**Comment by viragumathe5** [comment]
I am not at all good with JS 
so that's the real problem

**Comment by mrmaxguns** [comment]
Interesting, I will look into that. So you are saying we need to update the wiki and also the main page?

**Comment by cclauss** [comment]
Let's have one page but have all the links point to that one page.

**Comment by mrmaxguns** [comment]
> Let's have one page but have all the links point to that one page.

So just have one main page that all the links point to? Will the main page just explain about `TheAlgorithms`?

**Comment by cclauss** [comment]
You guys can get as fancy as you want...  I am not a web designer.  It should be appealing, respectful, and encourage visitors to both learn and participate but I have no other requirements.

**Comment by mrmaxguns** [comment]
Ok thank you very much for explaining. Let's see if we can do something awesome.

**Comment by mrmaxguns** [comment]
Changes should now be visible on [the site](https://thealgorithms.github.io/)

**Comment by cclauss** [comment]
Not.

**Comment by itsvinayak** [comment]
@cclauss  current website https://thealgorithms.github.io/website/ is really good why not just port 
https://thealgorithms.github.io/website/ -> https://thealgorithms.github.io/

**Comment by mrmaxguns** [comment]
@itsvinayak thank you for updating the webpage

**Comment by cclauss** [comment]
Jupyter seems to have been dropped:-(

https://github.com/TheAlgorithms/Algorithms-Explanation Too

**Comment by kvedala** [comment]
Has a consensus been reached on which repo to keep as a the main Website?

**Comment by mrmaxguns** [comment]
Closing this now that https://github.com/TheAlgorithms/website hosts the official site, and thealgorithms.github.io redirects to it.
