### ISSUE TITLE
The Gitter section on the navbar is still a broken link

### ISSUE THREAD

**Issue by mrmaxguns** [TheAlgorithms/TheAlgorithms.github.io#20]
It has come to my attention that the navigation bar on the site has a broken `Gitter` link that leads to `#Gitter`. Although pull request #6 was attempted to address this issue, it merely duplicated the `GitHub` section, which resulted in two `GitHub` sections. This was reversed with pull request #10. So now, this link remains broken, just as it was before. There are 3 possible options to address this issue:

1. Change the link's `href` to TheAlgorithms gitter page at [gitter.im](https://gitter.im/TheAlgorithms).
2. Create a Gitter section on the site (with the anchor `#Gitter).
3. Remove Gitter from the navbar entirely.

I hope to see a fix soon!

**Comment by Panquesito7** [comment]
Please create a pull request. Maintainers will review it (and merge it). Thank you! 🙂

**Comment by mrmaxguns** [comment]
Ok, working on it.

- [x] Fix broken link
- [x] Open pull request
- [x] Pull request merged

**Comment by mrmaxguns** [comment]
Pull request has been opened
