### ISSUE TITLE
There's a problem with the website on mobile view.

### ISSUE THREAD

**Issue by VikrantReddy** [TheAlgorithms/TheAlgorithms.github.io#8]
![image](https://user-images.githubusercontent.com/56089699/82380645-6e787e00-9a46-11ea-81ba-6a64c0739537.png)

There are a few bugs in the site's mobile view

**Comment by cclauss** [comment]
No need to ask for permission...  Just do it.

**Comment by VikrantReddy** [comment]
Okay, Thanks.
